/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Soft_Intelligent.co.ControlPuerta.Vista;

/**
 *
 * @author luisafernanda
 */
import javax.swing.JOptionPane;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import Soft_Intelligent.co.ControlPuerta.Modelo.ConectMySql;
import Soft_Intelligent.co.ControlPuerta.Modelo.EstadoGeneral;
import Soft_Intelligent.co.ControlPuerta.controlpuerta.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.math.MathContext;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JTextField;

public class Logi extends JFrame implements ActionListener {

    /**
     * Creates new form Logi
     */
    
    private JLabel labelTitulo;
    JTable miTabla1;
    JScrollPane mibarra1;
    JTextField Field;
    JTextField Field2;
    JTextField Field3;
    JTextField Field4;
    JLabel Label;
    JButton Boton1;
    JButton Boton2;
    JButton Boton3;
    String Estado;
    String Nombre;
    String Ubicacion;
    String IP;
    LogModeControl coneg;

    private ArrayList<LogModeControl> miLista;
    
    public static String ELIMINAR = "ELIMINAR";
    public static String ADICIONAR = "ADICIONAR";

    EstadoGeneral bdeg;

    public Logi() {
        setSize(800, 400);
        setTitle("Puerta : Login");
        setLocationRelativeTo(null);
        setResizable(false);

        miLista = new ArrayList();

        InicializaFormulario();
        InicializaTabla();
        construirTabla();
        InicializaBotones();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        bdeg = new EstadoGeneral();

    }
    
    private void InicializaFormulario() {

        Label = new JLabel("Puerta");
        Label.setBounds(27, 70, 230, 30);
        getContentPane().add(Label);

        Field = new JTextField();
        Field.setBounds(100, 70, 230, 30);
        getContentPane().add(Field);

        Label = new JLabel("IP");
        Label.setBounds(27, 110, 230, 30);
        getContentPane().add(Label);

        Field2 = new JTextField();
        Field2.setBounds(100, 110, 230, 30);
        getContentPane().add(Field2);

        Label = new JLabel("Hora Inicial");
        Label.setBounds(380, 70, 230, 30);
        getContentPane().add(Label);

        Field3 = new JTextField();
        Field3.setBounds(453, 70, 230, 30);
        getContentPane().add(Field3);

        Label = new JLabel("Hora Final");
        Label.setBounds(380, 110, 230, 30);
        getContentPane().add(Label);

        Field4 = new JTextField();
        Field4.setBounds(453, 110, 230, 30);
        getContentPane().add(Field4);
        
        Label = new JLabel("Estado");
        Label.setBounds(380, 110, 230, 30);
        getContentPane().add(Label);

        Field4 = new JTextField();
        Field4.setBounds(453, 110, 230, 30);
        getContentPane().add(Field4);
        
        Label = new JLabel("Ubicacion");
        Label.setBounds(380, 110, 230, 30);
        getContentPane().add(Label);

        Field4 = new JTextField();
        Field4.setBounds(453, 110, 230, 30);
        getContentPane().add(Field4);
        
        Label = new JLabel("Nombre de Usuario");
        Label.setBounds(380, 110, 230, 30);
        getContentPane().add(Label);

        Field4 = new JTextField();
        Field4.setBounds(453, 110, 230, 30);
        getContentPane().add(Field4);

        coneg = new LogModeControl();

    }
    
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
    private void InicializaTabla() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void construirTabla() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void InicializaBotones() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
